#define YY_CHAR char
#line 1 "/usr/local/lib/flexskel.cc"
/* A lexical scanner generated by flex */
/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */
/* institutional financial group  */

/* theses symbols are added before this file */
/* #define YY_CHAR 'unsigned char' if 8bit or 'char' if 7bit */
/* #define FLEX_DEBUG if debug mode */
#define FLEX_SCANNER
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
/* Old MSC, before c7 */
#ifdef MSDOS
#ifndef _MSDOS
#define _MSDOS
#endif
#endif
/* turboc */
#ifdef __MSDOS__
#ifndef _MSDOS
#define _MSDOS
#endif
#endif

#ifdef __cplusplus
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#ifndef _MSDOS
//#include <osfcn.h>
#endif
#else   /* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
int read();
#else
#include <stdlib.h>
#endif  /* __GNUC__ */
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif  /* __STDC__ */
#endif  /* ! __cplusplus */
#ifdef __TURBOC__
#define YY_USE_CONST
#endif
#include <stdio.h>


/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
/* the "const" storage-class-modifier is valid */
#ifndef YY_USE_CONST
#define const
#endif
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif


/*********************/
/* parameters        */

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* size of default input buffer */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) 
#endif

/***********************************/
/* to be redefined for application */

/* returned upon end-of-file */
#define YY_END_TOK 0
/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* code executed at the end of each rule */
#define YY_BREAK break;

/* #define YY_USER_ACTION */
/* #define YY_USER_INIT */


#ifndef YY_USE_CLASS
/* copy whatever the last rule matched to the standard output */
/* cast to (char *) is because for 8-bit chars, yy___text is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yy___text, yy___leng, 1, yy___out )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifdef _MSDOS
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread(buf,1,max_size,yy___in)) < 0 ) \
	    YY_FATAL_ERROR( "fread() in flex scanner failed" );
#else
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yy___in), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );

#endif
/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, yy___stderr  ); \
		(void) putc( '\n', yy___stderr  ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1


/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 
#else 
/* c++ */
#define ECHO yy___echo()
#define YY_INPUT(buf,result,max_size) \
	if ( yy___input((char *)buf, result,max_size) < 0 ) \
	    YY_FATAL_ERROR( "YY_INPUT() in flex scanner failed" );

#define YY_FATAL_ERROR(msg) yy___fatal_error(msg)
#define yywrap() yy___wrap()

#endif
/***********************************/
/* not to be changed */
#define YY_NULL 0
#define YY_END_OF_BUFFER_CHAR 0
/* special action meaning "start processing a new file" */
#define YY_NEW_FILE yy___newfile 
/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)



/* % section 1 definitions go here */ 
#line 1 "ppddl.lex"
#define INITIAL 0
#define YY_PDDL_Scanner_FLEX_SCANNER
#include "scanner.h"
#line 40 "ppddl.lex"
#line 196 "/usr/local/lib/flexskel.cc"

#define yy___stderr YY_PDDL_Scanner_ERRFILE
#define yy___text YY_PDDL_Scanner_TEXT
#define yy___leng YY_PDDL_Scanner_LENG
#define yy___in YY_PDDL_Scanner_IN
#define yy___out YY_PDDL_Scanner_OUT
#define yy___newfile \
	do \
		{ \
		YY_PDDL_Scanner_INIT_BUFFER( YY_PDDL_Scanner_CURRENT_BUFFER, yy___in ); \
		YY_PDDL_Scanner_LOAD_BUFFER_STATE(); \
		} \
	while ( 0 )
#if YY_PDDL_Scanner_DEBUG != 0
#define yy___flex_debug YY_PDDL_Scanner_DEBUG_FLAG
#endif


#ifdef YY_USE_CLASS

#define yy___echo YY_PDDL_Scanner_ECHO
#define yy___input YY_PDDL_Scanner_INPUT
#define yy___fatal_error YY_PDDL_Scanner_FATAL_ERROR
#define yy___wrap YY_PDDL_Scanner_WRAP

#endif

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yy___text
 */
#define YY_DO_BEFORE_ACTION \
	yy___text = yy_bp; \
/* % code to fiddle yy___text and yy___leng for yymore() goes here */ \
	yy___leng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yy___text */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yy___text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yy___text )



struct yy_buffer_state
    {
    YY_PDDL_Scanner_IFILE  *yy_input_file;

    YY_PDDL_Scanner_CHAR *yy_ch_buf;               /* input buffer */
    YY_PDDL_Scanner_CHAR *yy_buf_pos;      /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;    

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */

#ifndef YY_USE_CLASS

#if YY_PDDL_Scanner_DEBUG != 0
int YY_PDDL_Scanner_DEBUG_FLAG=YY_PDDL_Scanner_DEBUG_INIT;
#endif
#define YY_CURRENT_BUFFER YY_PDDL_Scanner_CURRENT_BUFFER
static YY_BUFFER_STATE YY_PDDL_Scanner_CURRENT_BUFFER;
/* yy_hold_char holds the character lost when yy___text is formed */
static YY_PDDL_Scanner_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */

/* GLOBAL */
YY_PDDL_Scanner_CHAR *yy___text;
int yy___leng;

YY_PDDL_Scanner_IFILE  *yy___in = (YY_PDDL_Scanner_IFILE  *) 0;
YY_PDDL_Scanner_OFILE *yy___out = (YY_PDDL_Scanner_OFILE  *) 0;

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_PDDL_Scanner_CHAR *yy_c_buf_p = (YY_PDDL_Scanner_CHAR *) 0;
static int yy_init = 1;         /* whether we need to initialize */
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yy___in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_PDDL_Scanner_CHAR c, YY_PDDL_Scanner_CHAR *buf_ptr ));

#else
/* c++ */
#ifndef YY_PDDL_Scanner_ECHO_NOCODE
void YY_PDDL_Scanner_CLASS::yy___echo()
{YY_PDDL_Scanner_ECHO_CODE
}
#endif
#ifndef YY_PDDL_Scanner_INPUT_NOCODE
int  YY_PDDL_Scanner_CLASS::yy___input(char * buffer,int &result,int max_size)
{YY_PDDL_Scanner_INPUT_CODE
}
#endif
#ifndef YY_PDDL_Scanner_FATAL_ERROR_NOCODE
void YY_PDDL_Scanner_CLASS::yy___fatal_error(const char *msg)
{YY_PDDL_Scanner_FATAL_ERROR_CODE
}
#endif
#ifndef YY_PDDL_Scanner_WRAP_NOCODE
int  YY_PDDL_Scanner_CLASS::yy___wrap()
{YY_PDDL_Scanner_WRAP_CODE
}
#endif
void YY_PDDL_Scanner_CLASS::yy_initialize()
{
 yy___in=0;yy___out=0;yy_init = 1;
 yy_start=0;
 yy___text=0;yy___leng=0;
 YY_PDDL_Scanner_CURRENT_BUFFER=0;
 yy_did_buffer_switch_on_eof=0;
 yy_c_buf_p=0;yy_hold_char=0;yy_n_chars=0;
#if YY_PDDL_Scanner_DEBUG != 0
 YY_PDDL_Scanner_DEBUG_FLAG=YY_PDDL_Scanner_DEBUG_INIT;
#endif
}

YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_CLASS(YY_PDDL_Scanner_CONSTRUCTOR_PARAM) YY_PDDL_Scanner_CONSTRUCTOR_INIT
{yy_initialize();
 YY_PDDL_Scanner_CONSTRUCTOR_CODE;
}
YY_PDDL_Scanner_CLASS::~YY_PDDL_Scanner_CLASS() 
{YY_PDDL_Scanner_DESTRUCTOR_CODE;
 if(YY_PDDL_Scanner_CURRENT_BUFFER)
  YY_PDDL_Scanner_DELETE_BUFFER(YY_PDDL_Scanner_CURRENT_BUFFER);
}

#endif


#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

/* % data tables for the DFA go here */ 
#define YY_END_OF_BUFFER 60
typedef int yy_state_type;
static const short int yy_accept[316] =
    {   0,
       58,   58,   60,   59,    1,    3,    4,    5,    8,   58,
       59,   59,    9,   59,    6,    7,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,    1,   58,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,    0,    2,   55,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       39,   57,   57,   57,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   55,   55,
       30,   57,   57,   57,   57,   57,   57,   57,   33,   57,

       57,   57,   57,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   34,   56,
       56,   28,   56,   56,   56,   56,   56,   56,   47,   29,
       56,   45,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   57,   57,   57,   57,
       57,   57,   57,   57,   40,   57,   57,   56,   20,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   26,   56,   56,   56,   56,   13,

       56,   56,   57,   57,   10,   11,   57,   31,   32,   57,
       57,   57,   19,   56,   56,   56,   43,   24,   56,   46,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   21,
       17,   56,   51,   56,   57,   57,   57,   57,   42,   41,
       56,   56,   56,   18,   56,   44,   56,   56,   27,   56,
       56,   56,   56,   52,   56,   56,   57,   57,   57,   57,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   49,   57,   57,   57,   35,   25,   14,   56,   54,
       56,   56,   56,   56,   56,   56,   56,   57,   57,   57,
       56,   56,   16,   22,   56,   15,   56,   56,   57,   37,

       38,   56,   56,   56,   56,   48,   36,   56,   50,   23,
       12,   56,   56,   53,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    1,    1,    1,    6,    1,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,    1,
       10,    1,   11,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   14,
       12,    1,   13,    1,   14,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   14,    1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[40] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static const short int yy_base[324] =
    {   0,
        0,    0,  434,  913,  429,  913,  913,  913,  422,  413,
       26,  405,  913,    0,  913,  913,   60,   62,   64,   66,
       68,   70,   72,   74,   78,   80,   85,  400,  387,   82,
       88,   93,  105,  108,  110,  112,  114,  117,  122,  125,
      135,  138,  140,  142,  149,  151,  383,  913,  156,    0,
      158,  161,  165,  167,  171,  176,  178,  183,  186,  188,
      190,  194,  196,  198,    0,  202,  205,  207,  209,  218,
      222,  225,  227,  229,  234,  238,  244,  231,  249,  251,
      253,  259,  262,  264,  266,  273,  270,  275,    0,  280,
      284,  268,  290,  296,  292,  298,  308,  310,  312,  314,

      320,  322,  326,  328,  331,  333,  335,  340,  342,  352,
      355,  338,  359,  363,  369,  372,  376,  378,  381,  383,
      386,  392,  398,  400,  403,  405,  407,  361,  344,  410,
      412,  417,  420,  426,  430,  435,  437,  439,  441,  443,
      450,  452,  458,  454,  460,  463,  467,  469,  472,  476,
      483,  485,  487,  492,  331,  494,  497,  499,  504,  508,
      510,  512,  501,  514,  516,  534,  348,  323,  536,  538,
      544,  546,  550,  552,  554,  558,  556,  561,  565,  567,
      575,  577,  579,  581,  585,  588,  590,  592,  337,  598,
      602,  604,  606,  611,  618,  621,  623,  629,  631,  633,

      638,  635,  297,  290,  640,  646,  652,  654,  656,  658,
      660,  668,  663,  670,  672,  674,  676,  678,  682,  688,
      302,  691,  280,  695,  697,  699,  705,  715,  712,  719,
      721,  723,  729,  733,  276,  302,  735,  737,  739,  741,
      743,  745,  747,  749,  277,  751,  260,  754,  756,  761,
      767,  769,  771,  775,  777,  780,  268,  234,  232,  782,
      785,  787,  215,  211,  211,  789,  794,  798,  800,  802,
      811,  816,  193,  190,  178,  818,  821,  823,  167,    0,
      164,  829,  831,  833,  835,  837,  840,  147,  150,  141,
      124,  113,  843,  845,  847,  851,  853,  855,  116,    0,

        0,  100,  106,  860,  864,  866,    0,   90,    0,  868,
      871,   81,   82,    0,  913,  897,   79,  899,  901,  903,
      905,  907,  909
    } ;

static const short int yy_def[324] =
    {   0,
      315,    1,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  316,  315,  317,  315,  315,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  315,  315,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  316,  315,  320,  321,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  322,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  323,  320,
      318,  321,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  321,  321,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  322,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  321,  321,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  322,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,

      319,  319,  321,  321,  318,  318,  318,  318,  318,  318,
      318,  318,  319,  319,  319,  319,  319,  319,  319,  319,
      322,  319,  322,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  321,  321,  318,  318,  318,  318,
      319,  319,  319,  319,  322,  319,  322,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  321,  321,  321,  318,
      319,  319,  322,  322,  322,  319,  319,  319,  319,  319,
      319,  319,  321,  321,  321,  318,  319,  319,  322,  322,
      322,  319,  319,  319,  319,  319,  319,  321,  321,  321,
      322,  322,  319,  319,  319,  319,  319,  319,  321,  321,

      321,  322,  322,  319,  319,  319,  321,  322,  322,  319,
      319,  322,  322,  322,    0,  315,  315,  315,  315,  315,
      315,  315,  315
    } ;

static const short int yy_nxt[953] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   17,   17,   19,   20,   21,
       17,   17,   22,   17,   17,   17,   17,   23,   24,   25,
       17,   17,   17,   17,   26,   17,   27,   17,   17,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   30,
       30,   30,   40,   30,   41,   42,   30,   43,   44,   45,
       30,   46,   30,   30,   30,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   49,   54,   50,   50,   50,   50,   65,   65,   52,
       50,   50,   55,   65,   65,   53,   57,   58,   65,   65,

       59,   60,  314,   56,   67,   61,   64,   63,  313,   62,
       65,   65,  312,   65,   65,   65,   65,   65,   65,   65,
       65,   69,   65,   65,  309,   68,   71,   65,   65,   73,
       65,   65,  308,   70,  307,   76,   72,   74,  303,   77,
       65,   65,   75,   65,   65,   65,   65,   65,   65,   78,
       80,  302,   81,   79,   65,   65,   65,   65,   83,  301,
       84,   89,   89,   50,   50,   88,   50,   50,  300,   82,
       92,   50,   50,   50,  299,   85,   50,   50,   91,  292,
       86,   50,   50,   50,   50,  291,   93,   87,   50,   50,
       95,   50,   50,   50,   50,   50,   50,   94,   96,   50,

       50,   50,   50,   50,   50,  290,  100,   65,   65,   97,
       65,   65,   65,   65,   65,   65,  103,  289,   98,   99,
      102,  288,  101,   65,   65,  281,  106,   65,   65,  105,
       65,   65,   65,   65,   65,   65,   65,   65,  104,   65,
       65,  108,  280,   65,   65,  107,  110,  279,  112,   65,
       65,  109,  113,  115,   65,   65,   65,   65,   65,   65,
      275,  114,  274,  111,   65,   65,  116,   65,   65,   65,
       65,   65,   65,  273,  117,   65,   65,  120,   65,   65,
       65,   65,  265,  118,  119,   89,   89,  124,  123,   50,
       50,  122,  121,  128,  129,   50,   50,   50,   50,  125,

      126,   50,   50,   50,   50,  264,  127,  258,  132,  257,
      131,  247,  130,   50,   50,   50,   50,   50,   50,   50,
       50,  245,  134,  236,  135,   50,   50,   50,   50,  235,
      133,   50,   50,   65,   65,  137,   65,   65,   65,   65,
       65,   65,  136,   65,   65,   65,   65,   65,   65,  138,
      140,  223,  143,  139,  145,  204,  146,   65,   65,  141,
       65,   65,  203,  149,   65,   65,  189,  144,   65,   65,
      147,  142,  168,  148,   65,   65,  150,   65,   65,  167,
      151,   65,   65,  155,   65,   48,   65,   65,   65,   65,
      153,   65,   65,   29,  154,  157,  156,   65,   65,  158,

      159,   28,  152,   65,   65,   65,   65,   48,   65,   65,
       65,   65,   65,   65,  162,   50,   50,   50,   50,   29,
      160,  164,   50,   50,  161,   50,   50,  163,   29,  166,
       28,   50,   50,  315,  170,   50,   50,  169,  315,  165,
       50,   50,   50,   50,   50,   50,   50,   50,   65,   65,
      171,  173,  315,  172,  175,   65,   65,   65,   65,   65,
       65,  174,  176,   65,   65,   65,   65,  177,   65,   65,
      315,  178,   65,   65,   65,   65,  179,   65,   65,  315,
      180,   65,   65,  184,  315,  183,  315,  181,   65,   65,
       65,   65,   65,   65,  182,  315,  185,   65,   65,   65,

       65,  186,   65,   65,   65,   65,   65,   65,  188,   65,
       65,  315,  187,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,  191,  315,  190,  193,  192,  195,  315,
      194,  315,  196,  199,  201,  315,  198,  315,  197,   65,
       65,   50,   50,   50,   50,  315,  200,  315,  202,   50,
       50,   50,   50,  315,  205,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,  206,   65,   65,  315,  207,
       65,   65,   65,   65,  210,  209,  211,  315,  208,  315,
       65,   65,   65,   65,   65,   65,   65,   65,  213,  215,
       65,   65,  212,   65,   65,  221,   65,   65,   65,  315,

      214,  315,  216,   65,   65,  315,  217,   65,   65,   65,
       65,   65,   65,  315,  218,  220,   65,   65,  219,  315,
      225,  315,  227,   65,   65,  222,   65,   65,   65,   65,
      315,  226,  315,  224,   65,   65,   65,   65,   65,   65,
       65,   65,  228,   65,   65,   50,   50,  315,  229,  315,
      234,   50,   50,  315,  230,  315,  232,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,  231,   65,   65,
      233,  315,  238,   50,   50,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,  315,  239,   65,   65,  315,
      237,  315,  241,   65,   65,  240,   65,   65,  315,  242,

       65,   65,   65,   65,   65,   65,  315,  243,  315,  248,
       65,   65,  315,  249,  244,  315,  251,   65,   65,  252,
       65,   65,  315,  246,   65,   65,   65,   65,   65,   65,
      250,  315,  254,  253,   65,   65,  315,  255,   65,   65,
      259,   50,   50,   50,   50,   50,   50,   50,   65,   65,
       65,   65,  263,   65,   65,   65,   65,   65,  256,   65,
       65,   65,   65,  315,  260,  315,   65,   65,  315,  266,
      315,  261,   65,   65,   65,   65,   65,   65,  262,  267,
       65,   65,   65,   65,  315,   65,   65,   50,   50,  268,
       65,   65,   65,   65,   65,   65,  315,  270,  272,   65,

       65,  315,  269,   65,   65,   65,   65,   65,   65,  315,
      271,  315,  277,  315,  282,  276,   65,   65,  285,  278,
      286,   65,   65,   50,   50,  283,   65,   65,   65,   65,
      315,  284,  315,  287,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,  315,   65,   65,  293,   65,   65,
       65,   65,   65,   65,  315,  295,   65,   65,   65,   65,
       65,   65,  315,  294,  297,   65,   65,  296,  298,   65,
       65,   65,   65,   65,   65,  304,   65,   65,  315,  315,
      315,  315,  306,  315,  315,  315,  305,  310,  315,  315,
      315,  315,  315,  315,  315,  315,  311,   47,   47,   47,

       51,   51,   66,   66,   90,   90,   50,   50,   65,   65,
       89,   89,    3,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315
    } ;

static const short int yy_chk[953] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   17,   17,   18,   18,   19,
       19,   20,   20,   21,   21,   22,   22,   23,   23,   24,
       24,  317,   19,   25,   25,   26,   26,   30,   30,   18,
       27,   27,   19,   31,   31,   18,   21,   22,   32,   32,

       23,   24,  313,   20,   31,   24,   27,   26,  312,   25,
       33,   33,  308,   34,   34,   35,   35,   36,   36,   37,
       37,   32,   38,   38,  303,   31,   34,   39,   39,   35,
       40,   40,  302,   33,  299,   38,   34,   36,  292,   38,
       41,   41,   37,   42,   42,   43,   43,   44,   44,   39,
       41,  291,   42,   40,   45,   45,   46,   46,   43,  290,
       44,   49,   49,   51,   51,   46,   52,   52,  289,   42,
       53,   53,   54,   54,  288,   44,   55,   55,   52,  281,
       45,   56,   56,   57,   57,  279,   54,   45,   58,   58,
       56,   59,   59,   60,   60,   61,   61,   55,   56,   62,

       62,   63,   63,   64,   64,  275,   60,   66,   66,   57,
       67,   67,   68,   68,   69,   69,   64,  274,   58,   59,
       63,  273,   62,   70,   70,  265,   69,   71,   71,   68,
       72,   72,   73,   73,   74,   74,   78,   78,   67,   75,
       75,   71,  264,   76,   76,   70,   73,  263,   75,   77,
       77,   72,   76,   78,   79,   79,   80,   80,   81,   81,
      259,   77,  258,   74,   82,   82,   79,   83,   83,   84,
       84,   85,   85,  257,   80,   87,   87,   82,   86,   86,
       88,   88,  247,   80,   81,   90,   90,   86,   85,   91,
       91,   84,   83,   92,   92,   93,   93,   95,   95,   87,

       88,   94,   94,   96,   96,  245,   88,  236,   95,  235,
       94,  223,   93,   97,   97,   98,   98,   99,   99,  100,
      100,  221,   97,  204,   98,  101,  101,  102,  102,  203,
       96,  103,  103,  104,  104,  101,  105,  105,  106,  106,
      107,  107,  100,  112,  112,  108,  108,  109,  109,  102,
      104,  189,  107,  103,  108,  168,  109,  110,  110,  105,
      111,  111,  167,  112,  113,  113,  155,  107,  114,  114,
      110,  106,  129,  111,  115,  115,  113,  116,  116,  128,
      114,  117,  117,  118,  118,   47,  119,  119,  120,  120,
      116,  121,  121,   29,  117,  119,  118,  122,  122,  120,

      120,   28,  115,  123,  123,  124,  124,   12,  125,  125,
      126,  126,  127,  127,  123,  130,  130,  131,  131,   10,
      121,  125,  132,  132,  122,  133,  133,  124,    9,  127,
        5,  134,  134,    3,  131,  135,  135,  130,    0,  126,
      136,  136,  137,  137,  138,  138,  139,  139,  140,  140,
      132,  134,    0,  133,  136,  141,  141,  142,  142,  144,
      144,  135,  137,  143,  143,  145,  145,  138,  146,  146,
        0,  140,  147,  147,  148,  148,  141,  149,  149,    0,
      143,  150,  150,  147,    0,  146,    0,  144,  151,  151,
      152,  152,  153,  153,  145,    0,  148,  154,  154,  156,

      156,  151,  157,  157,  158,  158,  163,  163,  154,  159,
      159,    0,  153,  160,  160,  161,  161,  162,  162,  164,
      164,  165,  165,  157,    0,  156,  159,  158,  161,    0,
      160,    0,  161,  163,  165,    0,  162,    0,  161,  166,
      166,  169,  169,  170,  170,    0,  164,    0,  166,  171,
      171,  172,  172,    0,  169,  173,  173,  174,  174,  175,
      175,  177,  177,  176,  176,  170,  178,  178,    0,  171,
      179,  179,  180,  180,  174,  173,  176,    0,  172,    0,
      181,  181,  182,  182,  183,  183,  184,  184,  178,  181,
      185,  185,  177,  186,  186,  187,  187,  188,  188,    0,

      180,    0,  182,  190,  190,    0,  183,  191,  191,  192,
      192,  193,  193,    0,  184,  186,  194,  194,  185,    0,
      191,    0,  193,  195,  195,  188,  196,  196,  197,  197,
        0,  192,    0,  190,  198,  198,  199,  199,  200,  200,
      202,  202,  194,  201,  201,  205,  205,    0,  196,    0,
      202,  206,  206,    0,  197,    0,  199,  207,  207,  208,
      208,  209,  209,  210,  210,  211,  211,  198,  213,  213,
      201,    0,  210,  212,  212,  214,  214,  215,  215,  216,
      216,  217,  217,  218,  218,    0,  211,  219,  219,    0,
      207,    0,  214,  220,  220,  212,  222,  222,    0,  215,

      224,  224,  225,  225,  226,  226,    0,  216,    0,  224,
      227,  227,    0,  224,  219,    0,  226,  229,  229,  227,
      228,  228,    0,  222,  230,  230,  231,  231,  232,  232,
      225,    0,  229,  228,  233,  233,    0,  232,  234,  234,
      237,  237,  238,  238,  239,  239,  240,  240,  241,  241,
      242,  242,  243,  243,  244,  244,  246,  246,  234,  248,
      248,  249,  249,    0,  238,    0,  250,  250,    0,  248,
        0,  241,  251,  251,  252,  252,  253,  253,  242,  250,
      254,  254,  255,  255,    0,  256,  256,  260,  260,  251,
      261,  261,  262,  262,  266,  266,    0,  253,  256,  267,

      267,    0,  252,  268,  268,  269,  269,  270,  270,    0,
      255,    0,  261,    0,  266,  260,  271,  271,  269,  262,
      270,  272,  272,  276,  276,  267,  277,  277,  278,  278,
        0,  268,    0,  271,  282,  282,  283,  283,  284,  284,
      285,  285,  286,  286,    0,  287,  287,  282,  293,  293,
      294,  294,  295,  295,    0,  284,  296,  296,  297,  297,
      298,  298,    0,  283,  286,  304,  304,  285,  287,  305,
      305,  306,  306,  310,  310,  295,  311,  311,    0,    0,
        0,    0,  298,    0,    0,    0,  297,  304,    0,    0,
        0,    0,    0,    0,    0,    0,  305,  316,  316,  316,

      318,  318,  319,  319,  320,  320,  321,  321,  322,  322,
      323,  323,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

#if YY_PDDL_Scanner_DEBUG != 0
static const short int yy_rule_linenum[59] =
    {   0,
       42,   43,   47,   52,   53,   54,   55,   56,   57,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   77,   78,   79,
       80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
       90,   91,   92,   93,   94,   95,   96,   98,   99,  100,
      101,  102,  103,  104,  107,  115,  119,  144
    } ;

#endif
/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#line 376 "/usr/local/lib/flexskel.cc"
#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
#else
#define yy_get_previous_state() ((yy_state_type)(yy_get_previous_state_()))
#define yy_try_NUL_trans(c) ((yy_state_type)(yy_try_NUL_trans_(c)))
#endif

#ifndef YY_USE_CLASS
#ifdef YY_PDDL_Scanner_LEX_DEFINED
YY_PDDL_Scanner_LEX_RETURN YY_PDDL_Scanner_LEX ( YY_PDDL_Scanner_LEX_PARAM )
YY_PDDL_Scanner_LEX_PARAM_DEF
#else
YY_DECL
#endif
#else
YY_PDDL_Scanner_LEX_RETURN YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_LEX ( YY_PDDL_Scanner_LEX_PARAM)

#endif
    {
    register yy_state_type yy_current_state;
    register YY_PDDL_Scanner_CHAR *yy_cp, *yy_bp;
    register int yy_act;

/* % user's declarations go here */ 


/* % end of prolog */ 
#line 401 "/usr/local/lib/flexskel.cc"

    if ( yy_init )
	{
	 
	 {
	 YY_USER_INIT;
	 }
	if ( ! yy_start )
	    yy_start = 1;       /* first start state */

	if ( ! yy___in )
	    yy___in = YY_PDDL_Scanner_IFILE_DEFAULT;

	if ( ! yy___out )
	    yy___out = YY_PDDL_Scanner_OFILE_DEFAULT;

	if ( YY_PDDL_Scanner_CURRENT_BUFFER )
	    YY_PDDL_Scanner_INIT_BUFFER( YY_PDDL_Scanner_CURRENT_BUFFER, yy___in );
	else
	    YY_PDDL_Scanner_CURRENT_BUFFER = YY_PDDL_Scanner_CREATE_BUFFER( yy___in, YY_BUF_SIZE );

	YY_PDDL_Scanner_LOAD_BUFFER_STATE();
	yy_init=0;
	}

    while ( 1 )         /* loops until end-of-file is reached */
	{
/* % yymore()-related code goes here */ 
#line 429 "/usr/local/lib/flexskel.cc"
	yy_cp = yy_c_buf_p;

	/* support of yy___text */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

/* % code to set up and find next match goes here */ 
	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 315 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;
#line 440 "/usr/local/lib/flexskel.cc"

yy_find_action:
/* % code to find the action number goes here */ 
	yy_act = yy_accept[yy_current_state];
#line 443 "/usr/local/lib/flexskel.cc"

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */
#if YY_PDDL_Scanner_DEBUG != 0
	if ( yy___flex_debug )
		{
		if ( yy_act == 0 )
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , "--scanner backtracking\n" );
#else
			yy___stderr <<"--scanner backtracking"<<endl;
#endif
		else if ( yy_act < YY_END_OF_BUFFER -1 )
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting rule at line %d (\"%s\")\n",
			 yy_rule_linenum[yy_act], yy___text );
#else
			yy___stderr <<"--accepting rule at line "
                          <<(int)yy_rule_linenum[yy_act]
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER -1 )
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting default rule (\"%s\")\n",
			 yy___text );
#else
			yy___stderr <<"--accepting default rule"
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER )
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , "--(end of buffer or a NUL)\n" );
#else
			yy___stderr <<"--(end of buffer or a NUL)"<<endl;
#endif
		else
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , "--EOF\n" );
#else
			yy___stderr <<"--EOF"<<endl;
#endif
		}
#endif
	switch ( yy_act )
	    {
/* % actions go here */ 
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
#line 42 "ppddl.lex"
;
	YY_BREAK
case 2:
#line 43 "ppddl.lex"
{ _line_no++;
                             if( _trace_line )
                                 cerr << endl << "LINE: " << _line_no << endl;
                           }
	YY_BREAK
case 3:
#line 47 "ppddl.lex"
{ _line_no++;
                             if( _trace_line )
                                 cerr << endl << "LINE: " << _line_no << endl;
                           }
	YY_BREAK
case 4:
#line 52 "ppddl.lex"
{ return PDDL_Parser::TK_OPEN; }
	YY_BREAK
case 5:
#line 53 "ppddl.lex"
{ return PDDL_Parser::TK_CLOSE; }
	YY_BREAK
case 6:
#line 54 "ppddl.lex"
{ return PDDL_Parser::TK_OPEN_SQ; }
	YY_BREAK
case 7:
#line 55 "ppddl.lex"
{ return PDDL_Parser::TK_CLOSE_SQ; }
	YY_BREAK
case 8:
#line 56 "ppddl.lex"
{ return PDDL_Parser::TK_HYPHEN; }
	YY_BREAK
case 9:
#line 57 "ppddl.lex"
{ return PDDL_Parser::TK_EQ; }
	YY_BREAK
case 10:
#line 59 "ppddl.lex"
{ return PDDL_Parser::KW_DEFINE; }
	YY_BREAK
case 11:
#line 60 "ppddl.lex"
{ return PDDL_Parser::KW_DOMAIN; }
	YY_BREAK
case 12:
#line 61 "ppddl.lex"
{ return PDDL_Parser::KW_REQS; }
	YY_BREAK
case 13:
#line 62 "ppddl.lex"
{ return PDDL_Parser::KW_TYPES; }
	YY_BREAK
case 14:
#line 63 "ppddl.lex"
{ return PDDL_Parser::KW_CONSTANTS; }
	YY_BREAK
case 15:
#line 64 "ppddl.lex"
{ return PDDL_Parser::KW_PREDS; }
	YY_BREAK
case 16:
#line 65 "ppddl.lex"
{ return PDDL_Parser::KW_OBSERVABLE; }
	YY_BREAK
case 17:
#line 66 "ppddl.lex"
{ return PDDL_Parser::KW_STICKY; }
	YY_BREAK
case 18:
#line 67 "ppddl.lex"
{ return PDDL_Parser::KW_FLUENTS; }
	YY_BREAK
case 19:
#line 68 "ppddl.lex"
{ return PDDL_Parser::KW_ACTION; }
	YY_BREAK
case 20:
#line 69 "ppddl.lex"
{ return PDDL_Parser::KW_AXIOM; }
	YY_BREAK
case 21:
#line 70 "ppddl.lex"
{ return PDDL_Parser::KW_SENSOR; }
	YY_BREAK
case 22:
#line 71 "ppddl.lex"
{ return PDDL_Parser::KW_ARGS; }
	YY_BREAK
case 23:
#line 72 "ppddl.lex"
{ return PDDL_Parser::KW_PRE; }
	YY_BREAK
case 24:
#line 73 "ppddl.lex"
{ return PDDL_Parser::KW_EFFECT; }
	YY_BREAK
case 25:
#line 74 "ppddl.lex"
{ return PDDL_Parser::KW_COND; }
	YY_BREAK
case 26:
#line 75 "ppddl.lex"
{ return PDDL_Parser::KW_SENSE; }
	YY_BREAK
case 27:
#line 76 "ppddl.lex"
{ return PDDL_Parser::KW_OBSERVE; }
	YY_BREAK
case 28:
#line 77 "ppddl.lex"
{ return PDDL_Parser::KW_BODY; }
	YY_BREAK
case 29:
#line 78 "ppddl.lex"
{ return PDDL_Parser::KW_HEAD; }
	YY_BREAK
case 30:
#line 79 "ppddl.lex"
{ return PDDL_Parser::KW_AND; }
	YY_BREAK
case 31:
#line 80 "ppddl.lex"
{ return PDDL_Parser::KW_EXISTS; }
	YY_BREAK
case 32:
#line 81 "ppddl.lex"
{ return PDDL_Parser::KW_FORALL; }
	YY_BREAK
case 33:
#line 82 "ppddl.lex"
{ return PDDL_Parser::KW_NOT; }
	YY_BREAK
case 34:
#line 83 "ppddl.lex"
{ return PDDL_Parser::KW_WHEN; }
	YY_BREAK
case 35:
#line 84 "ppddl.lex"
{ return PDDL_Parser::KW_INVARIANT; }
	YY_BREAK
case 36:
#line 85 "ppddl.lex"
{ return PDDL_Parser::KW_AT_LEAST_ONE; }
	YY_BREAK
case 37:
#line 86 "ppddl.lex"
{ return PDDL_Parser::KW_AT_MOST_ONE; }
	YY_BREAK
case 38:
#line 87 "ppddl.lex"
{ return PDDL_Parser::KW_EXACTLY_ONE; }
	YY_BREAK
case 39:
#line 88 "ppddl.lex"
{ return PDDL_Parser::KW_OR; }
	YY_BREAK
case 40:
#line 89 "ppddl.lex"
{ return PDDL_Parser::KW_ONEOF; }
	YY_BREAK
case 41:
#line 90 "ppddl.lex"
{ return PDDL_Parser::KW_UNKNOWN; }
	YY_BREAK
case 42:
#line 91 "ppddl.lex"
{ return PDDL_Parser::KW_PROBLEM; }
	YY_BREAK
case 43:
#line 92 "ppddl.lex"
{ return PDDL_Parser::KW_FORDOMAIN; }
	YY_BREAK
case 44:
#line 93 "ppddl.lex"
{ return PDDL_Parser::KW_OBJECTS; }
	YY_BREAK
case 45:
#line 94 "ppddl.lex"
{ return PDDL_Parser::KW_INIT; }
	YY_BREAK
case 46:
#line 95 "ppddl.lex"
{ return PDDL_Parser::KW_HIDDEN; }
	YY_BREAK
case 47:
#line 96 "ppddl.lex"
{ return PDDL_Parser::KW_GOAL; }
	YY_BREAK
case 48:
#line 98 "ppddl.lex"
{ return PDDL_Parser::KW_TRANSLATION; }
	YY_BREAK
case 49:
#line 99 "ppddl.lex"
{ return PDDL_Parser::KW_VARIABLE; }
	YY_BREAK
case 50:
#line 100 "ppddl.lex"
{ return PDDL_Parser::KW_OBS_VARIABLE; }
	YY_BREAK
case 51:
#line 101 "ppddl.lex"
{ return PDDL_Parser::KW_VALUES; }
	YY_BREAK
case 52:
#line 102 "ppddl.lex"
{ return PDDL_Parser::KW_SENSING; }
	YY_BREAK
case 53:
#line 103 "ppddl.lex"
{ return PDDL_Parser::KW_DEFAULT_SENSING; }
	YY_BREAK
case 54:
#line 104 "ppddl.lex"
{ return PDDL_Parser::KW_MODEL_FOR; }
	YY_BREAK
case 55:
#line 107 "ppddl.lex"
{ val.sym = _tab.inserta(yytext);
             if( val.sym->val == 0 )
                 return PDDL_Parser::TK_NEW_VAR_SYMBOL;
             if( ((PDDL_Base::Symbol*)val.sym->val)->sym_class_ == PDDL_Base::sym_variable )
                 return PDDL_Parser::TK_VAR_SYMBOL;
             return PDDL_Parser::TK_NEW_VAR_SYMBOL;
           }
	YY_BREAK
case 56:
#line 115 "ppddl.lex"
{ val.sym = _tab.inserta(yytext);
             return PDDL_Parser::TK_KEYWORD;
           }
	YY_BREAK
case 57:
#line 119 "ppddl.lex"
{ val.sym = _tab.inserta(yytext);
             if( val.sym->val == 0 ) {
                 return PDDL_Parser::TK_NEW_SYMBOL;
             } else {
                 switch (((PDDL_Base::Symbol*)val.sym->val)->sym_class_) {
                   case PDDL_Base::sym_object:
                     return PDDL_Parser::TK_OBJ_SYMBOL;
                   case PDDL_Base::sym_typename:
                     return PDDL_Parser::TK_TYPE_SYMBOL;
                   case PDDL_Base::sym_predicate:
                     return PDDL_Parser::TK_PRED_SYMBOL;
                   case PDDL_Base::sym_action:
                     return PDDL_Parser::TK_ACTION_SYMBOL;
                   case PDDL_Base::sym_sensor:
                     return PDDL_Parser::TK_SENSOR_SYMBOL;
                   case PDDL_Base::sym_axiom:
                     return PDDL_Parser::TK_AXIOM_SYMBOL;
                   case PDDL_Base::sym_varname:
                     return PDDL_Parser::TK_VARNAME_SYMBOL;
                   default:
                     return PDDL_Parser::TK_MISC_SYMBOL;
                 }
             }
           }
	YY_BREAK
case 58:
#line 144 "ppddl.lex"
{ val.ival = atoi(yytext); return PDDL_Parser::TK_INT; }
	YY_BREAK
case 59:
#line 146 "ppddl.lex"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();
#line 493 "/usr/local/lib/flexskel.cc"

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yy___text - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yy___text + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yy___text + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
/* % code to do backtracking for compressed tables and set up yy_cp goes here */ 
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
#line 541 "/usr/local/lib/flexskel.cc"
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yy___text,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yy___text + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yy___text + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#if YY_PDDL_Scanner_DEBUG != 0
#ifndef YY_PDDL_Scanner_IOSTREAM
		fprintf(yy___stderr , "action # %d\n", yy_act );
#else
		yy___stderr <<"action # "<<(int)yy_act<<endl;
#endif
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
	yyterminate();/* avoid the no return value error message on MS-C7/dos */
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
#ifndef YY_USE_CLASS
static int yy_get_next_buffer()
#else
int YY_PDDL_Scanner_CLASS::yy_get_next_buffer()
#endif
    {
    register YY_PDDL_Scanner_CHAR *dest = YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf;
    register YY_PDDL_Scanner_CHAR *source = yy___text - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yy___text;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( YY_PDDL_Scanner_CURRENT_BUFFER->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    YY_PDDL_Scanner_CURRENT_BUFFER->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    YY_PDDL_Scanner_CURRENT_BUFFER->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yy___text begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yy___text = &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state()
#else
long YY_PDDL_Scanner_CLASS::yy_get_previous_state_()
#endif
    {
    register yy_state_type yy_current_state;
    register YY_PDDL_Scanner_CHAR *yy_cp;

/* % code to get the start state into yy_current_state goes here */ 
    yy_current_state = yy_start;
#line 717 "/usr/local/lib/flexskel.cc"

    for ( yy_cp = yy___text + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
/* % code to find the next state goes here */ 
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 316 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
#line 721 "/usr/local/lib/flexskel.cc"
	}

#ifndef YY_USE_CLASS
    return ( yy_current_state );
#else
    return (long)( yy_current_state );
#endif
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif
#else
long YY_PDDL_Scanner_CLASS::yy_try_NUL_trans_(long yy_current_state_)
#endif

    {
#ifndef YY_USE_CLASS
#else
    yy_state_type yy_current_state=(yy_state_type)yy_current_state_;
#endif
    register int yy_is_jam;
/* % code to find the next state, and perhaps do backtracking, goes here */ 
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 316 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 315);
#line 755 "/usr/local/lib/flexskel.cc"

#ifndef YY_USE_CLASS
    return ( yy_is_jam ? 0 : yy_current_state );
#else
    return (long)( yy_is_jam ? 0 : yy_current_state );
#endif
    }

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static void yyunput( YY_PDDL_Scanner_CHAR c, register YY_PDDL_Scanner_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_PDDL_Scanner_CHAR c;
register YY_PDDL_Scanner_CHAR *yy_bp;
#endif
#else
void YY_PDDL_Scanner_CLASS::yyunput( YY_PDDL_Scanner_CHAR c, YY_PDDL_Scanner_CHAR *yy_bp )
#endif

    {
    register YY_PDDL_Scanner_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yy___text */
    *yy_cp = yy_hold_char;

    if ( yy_cp < YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_PDDL_Scanner_CHAR *dest =
	    &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_size + 2];
	register YY_PDDL_Scanner_CHAR *source =
	    &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[number_to_move];

	while ( source > YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_size;

	if ( yy_cp < YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yy___text again */
    }

#ifndef YY_USE_CLASS
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
#else
int YY_PDDL_Scanner_CLASS::input()
#endif
    {
    int c;
    YY_PDDL_Scanner_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yy___text = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yy___text + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yy___text + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
#else
		    YY_FATAL_ERROR( "unexpected last match in YY_PDDL_Scanner_CLASS::input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_RESTART( YY_PDDL_Scanner_IFILE  *input_file )
#else
void YY_PDDL_Scanner_RESTART( input_file )
YY_PDDL_Scanner_IFILE  *input_file;
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_RESTART ( YY_PDDL_Scanner_IFILE  *input_file )
#endif

    {
    YY_PDDL_Scanner_INIT_BUFFER( YY_PDDL_Scanner_CURRENT_BUFFER, input_file );
    YY_PDDL_Scanner_LOAD_BUFFER_STATE();
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#else
void YY_PDDL_Scanner_SWITCH_TO_BUFFER( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#endif

    {
    if ( YY_PDDL_Scanner_CURRENT_BUFFER == new_buffer )
	return;

    if ( YY_PDDL_Scanner_CURRENT_BUFFER )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_pos = yy_c_buf_p;
	YY_PDDL_Scanner_CURRENT_BUFFER->yy_n_chars = yy_n_chars;
	}

    YY_PDDL_Scanner_CURRENT_BUFFER = new_buffer;
    YY_PDDL_Scanner_LOAD_BUFFER_STATE();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_LOAD_BUFFER_STATE( void )
#else
void YY_PDDL_Scanner_LOAD_BUFFER_STATE()
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_LOAD_BUFFER_STATE(  )
#endif

    {
    yy_n_chars = YY_PDDL_Scanner_CURRENT_BUFFER->yy_n_chars;
    yy___text = yy_c_buf_p = YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_pos;
    yy___in = YY_PDDL_Scanner_CURRENT_BUFFER->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE YY_PDDL_Scanner_CREATE_BUFFER( YY_PDDL_Scanner_IFILE  *file, int size )
#else
YY_BUFFER_STATE YY_PDDL_Scanner_CREATE_BUFFER( file, size )
YY_PDDL_Scanner_IFILE  *file;
int size;
#endif
#else
YY_BUFFER_STATE YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_CREATE_BUFFER( YY_PDDL_Scanner_IFILE  *file, int size )
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in YY_PDDL_Scanner_CREATE_BUFFER()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_PDDL_Scanner_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in YY_PDDL_Scanner_CREATE_BUFFER()" );

    YY_PDDL_Scanner_INIT_BUFFER( b, file );

    return ( b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_DELETE_BUFFER( YY_BUFFER_STATE b )
#else
void YY_PDDL_Scanner_DELETE_BUFFER( b )
YY_BUFFER_STATE b;
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_DELETE_BUFFER( YY_BUFFER_STATE b )
#endif

    {
    if ( b == YY_PDDL_Scanner_CURRENT_BUFFER )
	YY_PDDL_Scanner_CURRENT_BUFFER = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_PDDL_Scanner_IFILE  *file )
#else
void YY_PDDL_Scanner_INIT_BUFFER( b, file )
YY_BUFFER_STATE b;
YY_PDDL_Scanner_IFILE  *file;
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_PDDL_Scanner_IFILE  *file)
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
#line 146 "ppddl.lex"


/*{FLOAT}    { val.rval = A_TO_NN(yytext); return PDDL_Parser::TK_FLOAT; }*/

int yywrap() {
    return 1;
}

void PDDL_Scanner::open_file(char* name, bool trace) {
    yyin = fopen(name, "r");
    if( !yyin ) {
        cerr << "error: can't open " << name << endl;
        exit(255);
    }
    _filename = name;
    if( _reset ) yy_init_buffer(YY_PDDL_Scanner_CURRENT_BUFFER, yyin);
    _reset = true;
    _line_no = 1;
    _trace_line = trace;
    yy_flex_debug = trace;
}

void PDDL_Scanner::close_file() {
    if( _filename != 0 ) {
        fclose(yyin);
        _filename = 0;
    }
}

