#define YY_CHAR char
#line 1 "/usr/local/lib/flexskel.cc"
/* A lexical scanner generated by flex */
/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */
/* institutional financial group  */

/* theses symbols are added before this file */
/* #define YY_CHAR 'unsigned char' if 8bit or 'char' if 7bit */
/* #define FLEX_DEBUG if debug mode */
#define FLEX_SCANNER
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
/* Old MSC, before c7 */
#ifdef MSDOS
#ifndef _MSDOS
#define _MSDOS
#endif
#endif
/* turboc */
#ifdef __MSDOS__
#ifndef _MSDOS
#define _MSDOS
#endif
#endif

#ifdef __cplusplus
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#ifndef _MSDOS
//#include <osfcn.h>
#endif
#else   /* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
int read();
#else
#include <stdlib.h>
#endif  /* __GNUC__ */
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif  /* __STDC__ */
#endif  /* ! __cplusplus */
#ifdef __TURBOC__
#define YY_USE_CONST
#endif
#include <stdio.h>


/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
/* the "const" storage-class-modifier is valid */
#ifndef YY_USE_CONST
#define const
#endif
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif


/*********************/
/* parameters        */

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* size of default input buffer */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) 
#endif

/***********************************/
/* to be redefined for application */

/* returned upon end-of-file */
#define YY_END_TOK 0
/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* code executed at the end of each rule */
#define YY_BREAK break;

/* #define YY_USER_ACTION */
/* #define YY_USER_INIT */


#ifndef YY_USE_CLASS
/* copy whatever the last rule matched to the standard output */
/* cast to (char *) is because for 8-bit chars, yy___text is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yy___text, yy___leng, 1, yy___out )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifdef _MSDOS
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread(buf,1,max_size,yy___in)) < 0 ) \
	    YY_FATAL_ERROR( "fread() in flex scanner failed" );
#else
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yy___in), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );

#endif
/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, yy___stderr  ); \
		(void) putc( '\n', yy___stderr  ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1


/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 
#else 
/* c++ */
#define ECHO yy___echo()
#define YY_INPUT(buf,result,max_size) \
	if ( yy___input((char *)buf, result,max_size) < 0 ) \
	    YY_FATAL_ERROR( "YY_INPUT() in flex scanner failed" );

#define YY_FATAL_ERROR(msg) yy___fatal_error(msg)
#define yywrap() yy___wrap()

#endif
/***********************************/
/* not to be changed */
#define YY_NULL 0
#define YY_END_OF_BUFFER_CHAR 0
/* special action meaning "start processing a new file" */
#define YY_NEW_FILE yy___newfile 
/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)



/* % section 1 definitions go here */ 
#line 1 "ppddl.lex"
#define INITIAL 0
#define YY_PDDL_Scanner_FLEX_SCANNER
#include "scanner.h"
#line 40 "ppddl.lex"
#line 196 "/usr/local/lib/flexskel.cc"

#define yy___stderr YY_PDDL_Scanner_ERRFILE
#define yy___text YY_PDDL_Scanner_TEXT
#define yy___leng YY_PDDL_Scanner_LENG
#define yy___in YY_PDDL_Scanner_IN
#define yy___out YY_PDDL_Scanner_OUT
#define yy___newfile \
	do \
		{ \
		YY_PDDL_Scanner_INIT_BUFFER( YY_PDDL_Scanner_CURRENT_BUFFER, yy___in ); \
		YY_PDDL_Scanner_LOAD_BUFFER_STATE(); \
		} \
	while ( 0 )
#if YY_PDDL_Scanner_DEBUG != 0
#define yy___flex_debug YY_PDDL_Scanner_DEBUG_FLAG
#endif


#ifdef YY_USE_CLASS

#define yy___echo YY_PDDL_Scanner_ECHO
#define yy___input YY_PDDL_Scanner_INPUT
#define yy___fatal_error YY_PDDL_Scanner_FATAL_ERROR
#define yy___wrap YY_PDDL_Scanner_WRAP

#endif

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yy___text
 */
#define YY_DO_BEFORE_ACTION \
	yy___text = yy_bp; \
/* % code to fiddle yy___text and yy___leng for yymore() goes here */ \
	yy___leng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yy___text */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yy___text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yy___text )



struct yy_buffer_state
    {
    YY_PDDL_Scanner_IFILE  *yy_input_file;

    YY_PDDL_Scanner_CHAR *yy_ch_buf;               /* input buffer */
    YY_PDDL_Scanner_CHAR *yy_buf_pos;      /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;    

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */

#ifndef YY_USE_CLASS

#if YY_PDDL_Scanner_DEBUG != 0
int YY_PDDL_Scanner_DEBUG_FLAG=YY_PDDL_Scanner_DEBUG_INIT;
#endif
#define YY_CURRENT_BUFFER YY_PDDL_Scanner_CURRENT_BUFFER
static YY_BUFFER_STATE YY_PDDL_Scanner_CURRENT_BUFFER;
/* yy_hold_char holds the character lost when yy___text is formed */
static YY_PDDL_Scanner_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */

/* GLOBAL */
YY_PDDL_Scanner_CHAR *yy___text;
int yy___leng;

YY_PDDL_Scanner_IFILE  *yy___in = (YY_PDDL_Scanner_IFILE  *) 0;
YY_PDDL_Scanner_OFILE *yy___out = (YY_PDDL_Scanner_OFILE  *) 0;

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_PDDL_Scanner_CHAR *yy_c_buf_p = (YY_PDDL_Scanner_CHAR *) 0;
static int yy_init = 1;         /* whether we need to initialize */
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yy___in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_PDDL_Scanner_CHAR c, YY_PDDL_Scanner_CHAR *buf_ptr ));

#else
/* c++ */
#ifndef YY_PDDL_Scanner_ECHO_NOCODE
void YY_PDDL_Scanner_CLASS::yy___echo()
{YY_PDDL_Scanner_ECHO_CODE
}
#endif
#ifndef YY_PDDL_Scanner_INPUT_NOCODE
int  YY_PDDL_Scanner_CLASS::yy___input(char * buffer,int &result,int max_size)
{YY_PDDL_Scanner_INPUT_CODE
}
#endif
#ifndef YY_PDDL_Scanner_FATAL_ERROR_NOCODE
void YY_PDDL_Scanner_CLASS::yy___fatal_error(const char *msg)
{YY_PDDL_Scanner_FATAL_ERROR_CODE
}
#endif
#ifndef YY_PDDL_Scanner_WRAP_NOCODE
int  YY_PDDL_Scanner_CLASS::yy___wrap()
{YY_PDDL_Scanner_WRAP_CODE
}
#endif
void YY_PDDL_Scanner_CLASS::yy_initialize()
{
 yy___in=0;yy___out=0;yy_init = 1;
 yy_start=0;
 yy___text=0;yy___leng=0;
 YY_PDDL_Scanner_CURRENT_BUFFER=0;
 yy_did_buffer_switch_on_eof=0;
 yy_c_buf_p=0;yy_hold_char=0;yy_n_chars=0;
#if YY_PDDL_Scanner_DEBUG != 0
 YY_PDDL_Scanner_DEBUG_FLAG=YY_PDDL_Scanner_DEBUG_INIT;
#endif
}

YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_CLASS(YY_PDDL_Scanner_CONSTRUCTOR_PARAM) YY_PDDL_Scanner_CONSTRUCTOR_INIT
{yy_initialize();
 YY_PDDL_Scanner_CONSTRUCTOR_CODE;
}
YY_PDDL_Scanner_CLASS::~YY_PDDL_Scanner_CLASS() 
{YY_PDDL_Scanner_DESTRUCTOR_CODE;
 if(YY_PDDL_Scanner_CURRENT_BUFFER)
  YY_PDDL_Scanner_DELETE_BUFFER(YY_PDDL_Scanner_CURRENT_BUFFER);
}

#endif


#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

/* % data tables for the DFA go here */ 
#define YY_END_OF_BUFFER 63
typedef int yy_state_type;
static const short int yy_accept[335] =
    {   0,
       61,   61,   63,   62,    1,    3,    4,    5,    8,   61,
       62,   62,    9,   62,    6,    7,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,    1,
       61,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,    0,    2,
       58,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   41,   60,   60,   60,   60,   60,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   58,   58,   32,   60,   60,   60,   60,

       60,   60,   60,   60,   35,   60,   60,   60,   60,   60,
       60,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   30,   60,   36,   59,
       59,   28,   59,   59,   59,   59,   59,   59,   49,   29,
       59,   47,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   60,   60,   60,   60,
       60,   60,   31,   60,   60,   42,   60,   60,   60,   59,
       20,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   26,   59,   59,   59,
       59,   13,   59,   59,   60,   60,   10,   11,   60,   33,
       34,   60,   60,   60,   60,   19,   59,   59,   59,   45,
       24,   59,   48,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   21,   17,   59,   59,   59,   60,   60,   60,
       60,   44,   60,   43,   59,   59,   59,   18,   59,   46,
       59,   59,   27,   59,   59,   59,   59,   54,   59,   59,
       59,   60,   60,   60,   60,   60,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   51,   60,
       60,   60,   37,   57,   25,   14,   59,   56,   59,   59,

       59,   59,   59,   59,   59,   53,   60,   60,   60,   59,
       59,   16,   22,   59,   15,   59,   59,   60,   39,   40,
       59,   59,   59,   59,   50,   38,   59,   52,   23,   12,
       59,   59,   55,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        5,    1,    1,    1,    6,    1,    1,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,    1,
       10,    1,   11,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   14,
       12,    1,   13,    1,   14,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   14,    1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[40] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static const short int yy_base[343] =
    {   0,
        0,    0,  455,  936,  449,  936,  936,  936,  442,  429,
       26,  431,  936,    0,  936,  936,   60,   62,   64,   66,
       69,   71,   73,   75,   79,   81,   85,   94,   88,  426,
      413,   99,  102,  106,  108,  114,  118,  120,  122,  125,
      135,  143,  146,  149,  151,  154,  159,  161,  411,  936,
      168,    0,  171,  176,  173,  179,  183,  186,  189,  196,
      198,  201,  205,  207,  210,  212,  214,  216,  219,    0,
      224,  226,  230,  236,  238,  241,  244,  249,  251,  257,
      261,  267,  271,  273,  275,  277,  281,  283,  289,  295,
      291,  286,  297,    0,  304,  306,  293,  315,  317,  319,

      321,  324,  327,  333,  337,  339,  343,  345,  354,  349,
      356,  358,  363,  365,  368,  372,  376,  383,  387,  389,
      391,  393,  401,  406,  410,  412,  415,  420,  417,  426,
      433,  435,  437,  439,  391,  376,  441,  447,  451,  454,
      458,  460,  465,  467,  469,  472,  474,  476,  483,  485,
      492,  487,  494,  496,  500,  502,  504,  506,  509,  516,
      520,  522,  525,  530,  367,  534,  536,  538,  542,  546,
      549,  551,  553,  555,  367,  564,  370,  347,  568,  574,
      577,  583,  585,  587,  589,  591,  598,  342,  593,  600,
      602,  604,  608,  613,  615,  618,  620,  625,  627,  629,

      351,  634,  638,  640,  642,  644,  649,  654,  658,  660,
      665,  667,  326,  671,  320,  313,  673,  677,  679,  682,
      686,  688,  690,  319,  694,  698,  700,  702,  704,  706,
      708,  713,  718,  317,  720,  303,  722,  725,  727,  729,
      733,  736,  741,  743,  748,  286,  754,  273,  299,  758,
      760,  762,  260,  764,  766,  768,  770,  772,  241,  775,
      242,  777,  779,  784,  790,  792,  794,  798,  800,  227,
      803,  253,  223,  217,  805,  206,  808,  810,  194,  174,
      185,  812,  817,  821,  823,  825,  834,  167,  839,  158,
      156,  143,  841,    0,  844,  846,  150,    0,  143,  852,

      854,  856,  858,  860,  863,    0,  126,  128,  126,  111,
      110,  866,  868,  870,  874,  876,  878,  115,    0,    0,
       97,  104,  883,  887,  889,    0,   95,    0,  891,  894,
       69,   68,    0,  936,  920,   71,  922,  924,  926,  928,
      930,  932
    } ;

static const short int yy_def[343] =
    {   0,
      334,    1,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  335,  334,  336,  334,  334,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  334,
      334,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  335,  334,
      339,  340,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  341,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  342,  339,  337,  340,  337,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  340,  340,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  341,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  341,  338,  340,  340,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  340,  337,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,

      341,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  341,  338,  340,  340,  337,  337,  337,  337,
      337,  337,  337,  340,  337,  338,  338,  338,  338,  338,
      338,  338,  338,  341,  338,  341,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  341,  338,  340,  340,  337,
      337,  337,  340,  337,  338,  338,  338,  338,  341,  338,
      341,  338,  338,  338,  338,  338,  338,  338,  338,  341,
      338,  340,  340,  340,  337,  340,  338,  338,  341,  341,
      341,  338,  338,  338,  338,  338,  338,  341,  338,  340,
      340,  340,  337,  340,  338,  338,  341,  341,  341,  338,

      338,  338,  338,  338,  338,  341,  340,  340,  340,  341,
      341,  338,  338,  338,  338,  338,  338,  340,  340,  340,
      341,  341,  338,  338,  338,  340,  341,  341,  338,  338,
      341,  341,  341,    0,  334,  334,  334,  334,  334,  334,
      334,  334
    } ;

static const short int yy_nxt[976] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   17,   17,   19,   20,   21,
       17,   17,   22,   17,   17,   17,   17,   23,   24,   25,
       17,   17,   26,   27,   28,   17,   29,   17,   17,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   32,
       32,   32,   42,   32,   43,   44,   32,   45,   46,   47,
       32,   48,   32,   32,   32,   52,   52,   52,   52,   52,
       52,   52,   52,   51,   52,   52,   52,   52,   52,   52,
       52,   52,   56,   59,   52,   52,   52,   52,  333,   54,
       52,   52,   57,   52,   52,   55,  332,   60,   61,   52,

       52,   62,   63,   58,   70,   70,   64,   70,   70,   69,
       65,   70,   70,   70,   70,   66,   67,  331,   72,   70,
       70,   68,  328,   70,   70,   70,   70,   70,   70,  327,
       70,   70,   76,  326,   74,  322,   75,   78,  321,   73,
       70,   70,   77,   81,  320,   79,  319,   82,   70,   70,
       80,   70,   70,  318,   70,   70,   70,   70,  311,   70,
       70,   85,   83,   86,   70,   70,   70,   70,  310,   88,
      309,   84,   89,   94,   94,   93,   52,   52,   97,   52,
       87,   52,   52,  308,   52,   52,  307,   90,   52,   52,
       91,   52,   52,   96,   52,   52,  306,   92,   98,  299,

      100,   52,   52,   52,   52,  298,   52,   52,  101,   99,
       52,   52,   52,   52,  102,   52,   52,   52,   52,   52,
       52,   52,   52,  106,   52,   52,  297,  103,  108,   70,
       70,   70,   70,  104,  105,   70,   70,  111,  107,  294,
      110,   70,   70,   70,   70,  292,   70,   70,  109,   70,
       70,  291,  113,  114,   70,   70,   70,   70,  290,  112,
      116,  288,   70,   70,  281,  115,   70,   70,  118,  280,
      117,  120,   70,   70,  276,  121,   70,   70,   70,   70,
       70,   70,   70,   70,  122,  119,   70,   70,   70,   70,
      124,   70,   70,  123,   70,   70,   70,   70,  125,  128,

       70,   70,   70,   70,  273,  132,  272,  126,  127,   94,
       94,   52,   52,  129,  270,  133,  130,  131,  135,  136,
       52,   52,   52,   52,   52,   52,   52,   52,  134,   52,
       52,  138,   52,   52,  261,  139,  259,  137,   52,   52,
      253,  142,   52,   52,   52,   52,  249,  143,   52,   52,
       52,   52,  248,  140,   52,   52,  141,  246,  145,   52,
       52,   52,   52,   70,   70,  236,  146,  144,   70,   70,
       70,   70,  147,   70,   70,  224,  148,   70,   70,  216,
      150,   70,   70,  149,  215,  153,  155,  213,   70,   70,
      156,  151,   70,   70,   70,   70,   70,   70,   70,   70,

      154,  157,  201,  152,  178,  158,   70,   70,  160,  177,
      161,   70,   70,   50,  159,   70,   70,  165,   70,   31,
       70,   70,   70,   70,  163,   70,   70,   30,  164,  167,
      166,   70,   70,   50,  162,   31,  168,  169,   70,   70,
       70,   70,   70,   70,  175,   70,   52,   52,   31,  172,
       30,  170,   52,   52,  334,  174,   52,   52,  171,   52,
       52,  176,  173,   52,   52,   52,   52,  334,  179,  180,
       52,   52,   52,   52,   52,   52,  183,  188,   52,   52,
       52,   52,   52,  334,  181,  184,  186,  182,   52,   52,
       70,   70,   70,   70,  187,  334,  185,   70,   70,   70,

       70,   70,   70,  334,  189,   70,   70,   70,   70,   70,
       70,   70,   70,  190,   70,   70,  192,  334,  191,  334,
      196,   70,   70,  334,  195,   70,   70,   70,   70,  193,
       70,   70,  334,  197,  194,   70,   70,  334,  198,   70,
       70,   70,   70,   70,   70,  334,  200,   70,   70,  334,
      199,   70,   70,  334,   70,   70,   70,   70,   70,   70,
       70,   70,  203,  334,  205,  202,  204,  207,  206,   70,
       70,  208,  334,   52,   52,  210,  334,  209,  214,   52,
       52,  334,   52,   52,  334,  211,  217,  212,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,

      334,  218,  219,   52,   52,   70,   70,   70,   70,   70,
       70,  222,  221,   70,   70,  220,  223,  334,   70,   70,
       70,   70,  228,   70,   70,   70,   70,  226,  334,  225,
       70,   70,  234,   70,   70,   70,  334,  227,  229,   70,
       70,  334,  230,   70,   70,   70,   70,   70,   70,   70,
       70,  231,  233,  232,   70,   70,  238,  334,  240,   70,
       70,  334,  235,   70,   70,   70,   70,  239,  334,  237,
       70,   70,   70,   70,  334,  241,   70,   70,   52,   52,
      334,  242,   52,   52,   52,   52,  247,   52,   52,  243,
      245,   52,   52,   52,   52,   52,   52,  334,  244,   52,

       52,  334,  251,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,  334,  252,  250,   70,   70,
      334,  254,  255,   70,   70,   70,   70,   70,   70,  256,
       70,   70,   70,   70,   70,   70,  262,  257,   70,   70,
      263,   70,   70,  266,  265,  258,   70,   70,   70,   70,
      334,  267,  260,   70,   70,  334,  268,  334,  264,   70,
       70,  334,  269,  274,   52,   52,   52,   52,   52,   52,
       52,   70,   70,   70,   70,  279,   70,   70,   70,  271,
       70,   70,   70,   70,   70,   70,  334,  275,  334,   70,
       70,  334,  282,  334,  277,   70,   70,   70,   70,   70,

       70,  278,  283,   70,   70,   70,   70,  334,   70,   70,
       52,   52,  284,   70,   70,   70,   70,   70,   70,  334,
      286,  289,   70,   70,  334,  285,   70,   70,   70,   70,
       70,   70,  334,  287,  334,  295,  334,  300,  293,   70,
       70,  303,  296,  304,   70,   70,   52,   52,  301,   70,
       70,   70,   70,  334,  302,  334,  305,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,  334,   70,   70,
      312,   70,   70,   70,   70,   70,   70,  334,  314,   70,
       70,   70,   70,   70,   70,  334,  313,  316,   70,   70,
      315,  317,   70,   70,   70,   70,   70,   70,  323,   70,

       70,  334,  334,  334,  334,  325,  334,  334,  334,  324,
      329,  334,  334,  334,  334,  334,  334,  334,  334,  330,
       49,   49,   49,   53,   53,   71,   71,   95,   95,   52,
       52,   70,   70,   94,   94,    3,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334
    } ;

static const short int yy_chk[976] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   17,   17,   18,   18,   19,
       19,   20,   20,  336,   21,   21,   22,   22,   23,   23,
       24,   24,   19,   21,   25,   25,   26,   26,  332,   18,
       27,   27,   19,   29,   29,   18,  331,   21,   22,   28,

       28,   23,   24,   20,   32,   32,   24,   33,   33,   29,
       25,   34,   34,   35,   35,   26,   27,  327,   33,   36,
       36,   28,  322,   37,   37,   38,   38,   39,   39,  321,
       40,   40,   36,  318,   34,  311,   35,   37,  310,   33,
       41,   41,   36,   40,  309,   38,  308,   40,   42,   42,
       39,   43,   43,  307,   44,   44,   45,   45,  299,   46,
       46,   43,   41,   44,   47,   47,   48,   48,  297,   45,
      292,   42,   46,   51,   51,   48,   53,   53,   55,   55,
       44,   54,   54,  291,   56,   56,  290,   46,   57,   57,
       47,   58,   58,   54,   59,   59,  288,   47,   56,  281,

       58,   60,   60,   61,   61,  280,   62,   62,   58,   57,
       63,   63,   64,   64,   59,   65,   65,   66,   66,   67,
       67,   68,   68,   63,   69,   69,  279,   60,   66,   71,
       71,   72,   72,   61,   62,   73,   73,   69,   65,  276,
       68,   74,   74,   75,   75,  274,   76,   76,   67,   77,
       77,  273,   73,   74,   78,   78,   79,   79,  272,   72,
       76,  270,   80,   80,  261,   75,   81,   81,   78,  259,
       77,   80,   82,   82,  253,   81,   83,   83,   84,   84,
       85,   85,   86,   86,   82,   79,   87,   87,   88,   88,
       84,   92,   92,   83,   89,   89,   91,   91,   85,   87,

       90,   90,   93,   93,  249,   91,  248,   85,   86,   95,
       95,   96,   96,   88,  246,   92,   89,   90,   97,   97,
       98,   98,   99,   99,  100,  100,  101,  101,   93,  102,
      102,   99,  103,  103,  236,  100,  234,   98,  104,  104,
      224,  103,  105,  105,  106,  106,  216,  104,  107,  107,
      108,  108,  215,  101,  110,  110,  102,  213,  107,  109,
      109,  111,  111,  112,  112,  201,  108,  106,  113,  113,
      114,  114,  109,  115,  115,  188,  110,  116,  116,  178,
      112,  117,  117,  111,  177,  115,  116,  175,  118,  118,
      117,  113,  119,  119,  120,  120,  121,  121,  122,  122,

      115,  118,  165,  114,  136,  119,  123,  123,  121,  135,
      122,  124,  124,   49,  120,  125,  125,  126,  126,   31,
      127,  127,  129,  129,  124,  128,  128,   30,  125,  127,
      126,  130,  130,   12,  123,   10,  128,  128,  131,  131,
      132,  132,  133,  133,  134,  134,  137,  137,    9,  131,
        5,  129,  138,  138,    3,  133,  139,  139,  130,  140,
      140,  134,  132,  141,  141,  142,  142,    0,  137,  138,
      143,  143,  144,  144,  145,  145,  141,  146,  146,  147,
      147,  148,  148,    0,  139,  142,  144,  140,  149,  149,
      150,  150,  152,  152,  145,    0,  143,  151,  151,  153,

      153,  154,  154,    0,  148,  155,  155,  156,  156,  157,
      157,  158,  158,  150,  159,  159,  153,    0,  151,    0,
      157,  160,  160,    0,  156,  161,  161,  162,  162,  154,
      163,  163,    0,  158,  155,  164,  164,    0,  161,  166,
      166,  167,  167,  168,  168,    0,  164,  169,  169,    0,
      163,  170,  170,    0,  171,  171,  172,  172,  173,  173,
      174,  174,  167,    0,  169,  166,  168,  171,  170,  176,
      176,  171,    0,  179,  179,  172,    0,  171,  176,  180,
      180,    0,  181,  181,    0,  173,  179,  174,  182,  182,
      183,  183,  184,  184,  185,  185,  186,  186,  189,  189,

        0,  180,  181,  187,  187,  190,  190,  191,  191,  192,
      192,  185,  184,  193,  193,  182,  187,    0,  194,  194,
      195,  195,  193,  196,  196,  197,  197,  190,    0,  189,
      198,  198,  199,  199,  200,  200,    0,  192,  194,  202,
      202,    0,  195,  203,  203,  204,  204,  205,  205,  206,
      206,  196,  198,  197,  207,  207,  203,    0,  205,  208,
      208,    0,  200,  209,  209,  210,  210,  204,    0,  202,
      211,  211,  212,  212,    0,  206,  214,  214,  217,  217,
        0,  208,  218,  218,  219,  219,  214,  220,  220,  209,
      211,  221,  221,  222,  222,  223,  223,    0,  210,  225,

      225,    0,  222,  226,  226,  227,  227,  228,  228,  229,
      229,  230,  230,  231,  231,    0,  223,  219,  232,  232,
        0,  225,  227,  233,  233,  235,  235,  237,  237,  228,
      238,  238,  239,  239,  240,  240,  237,  229,  241,  241,
      237,  242,  242,  240,  239,  232,  243,  243,  244,  244,
        0,  241,  235,  245,  245,    0,  242,    0,  238,  247,
      247,    0,  245,  250,  250,  251,  251,  252,  252,  254,
      254,  255,  255,  256,  256,  257,  257,  258,  258,  247,
      260,  260,  262,  262,  263,  263,    0,  251,    0,  264,
      264,    0,  262,    0,  255,  265,  265,  266,  266,  267,

      267,  256,  264,  268,  268,  269,  269,    0,  271,  271,
      275,  275,  265,  277,  277,  278,  278,  282,  282,    0,
      267,  271,  283,  283,    0,  266,  284,  284,  285,  285,
      286,  286,    0,  269,    0,  277,    0,  282,  275,  287,
      287,  285,  278,  286,  289,  289,  293,  293,  283,  295,
      295,  296,  296,    0,  284,    0,  287,  300,  300,  301,
      301,  302,  302,  303,  303,  304,  304,    0,  305,  305,
      300,  312,  312,  313,  313,  314,  314,    0,  302,  315,
      315,  316,  316,  317,  317,    0,  301,  304,  323,  323,
      303,  305,  324,  324,  325,  325,  329,  329,  314,  330,

      330,    0,    0,    0,    0,  317,    0,    0,    0,  316,
      323,    0,    0,    0,    0,    0,    0,    0,    0,  324,
      335,  335,  335,  337,  337,  338,  338,  339,  339,  340,
      340,  341,  341,  342,  342,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

#if YY_PDDL_Scanner_DEBUG != 0
static const short int yy_rule_linenum[62] =
    {   0,
       42,   43,   47,   52,   53,   54,   55,   56,   57,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   77,   78,   79,
       80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
       90,   91,   92,   93,   94,   95,   96,   97,   98,  100,
      101,  102,  103,  104,  105,  106,  107,  110,  118,  122,
      147
    } ;

#endif
/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#line 376 "/usr/local/lib/flexskel.cc"
#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
#else
#define yy_get_previous_state() ((yy_state_type)(yy_get_previous_state_()))
#define yy_try_NUL_trans(c) ((yy_state_type)(yy_try_NUL_trans_(c)))
#endif

#ifndef YY_USE_CLASS
#ifdef YY_PDDL_Scanner_LEX_DEFINED
YY_PDDL_Scanner_LEX_RETURN YY_PDDL_Scanner_LEX ( YY_PDDL_Scanner_LEX_PARAM )
YY_PDDL_Scanner_LEX_PARAM_DEF
#else
YY_DECL
#endif
#else
YY_PDDL_Scanner_LEX_RETURN YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_LEX ( YY_PDDL_Scanner_LEX_PARAM)

#endif
    {
    register yy_state_type yy_current_state;
    register YY_PDDL_Scanner_CHAR *yy_cp, *yy_bp;
    register int yy_act;

/* % user's declarations go here */ 


/* % end of prolog */ 
#line 401 "/usr/local/lib/flexskel.cc"

    if ( yy_init )
	{
	 
	 {
	 YY_USER_INIT;
	 }
	if ( ! yy_start )
	    yy_start = 1;       /* first start state */

	if ( ! yy___in )
	    yy___in = YY_PDDL_Scanner_IFILE_DEFAULT;

	if ( ! yy___out )
	    yy___out = YY_PDDL_Scanner_OFILE_DEFAULT;

	if ( YY_PDDL_Scanner_CURRENT_BUFFER )
	    YY_PDDL_Scanner_INIT_BUFFER( YY_PDDL_Scanner_CURRENT_BUFFER, yy___in );
	else
	    YY_PDDL_Scanner_CURRENT_BUFFER = YY_PDDL_Scanner_CREATE_BUFFER( yy___in, YY_BUF_SIZE );

	YY_PDDL_Scanner_LOAD_BUFFER_STATE();
	yy_init=0;
	}

    while ( 1 )         /* loops until end-of-file is reached */
	{
/* % yymore()-related code goes here */ 
#line 429 "/usr/local/lib/flexskel.cc"
	yy_cp = yy_c_buf_p;

	/* support of yy___text */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

/* % code to set up and find next match goes here */ 
	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 335 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 334 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;
#line 440 "/usr/local/lib/flexskel.cc"

yy_find_action:
/* % code to find the action number goes here */ 
	yy_act = yy_accept[yy_current_state];
#line 443 "/usr/local/lib/flexskel.cc"

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */
#if YY_PDDL_Scanner_DEBUG != 0
	if ( yy___flex_debug )
		{
		if ( yy_act == 0 )
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , "--scanner backtracking\n" );
#else
			yy___stderr <<"--scanner backtracking"<<endl;
#endif
		else if ( yy_act < YY_END_OF_BUFFER -1 )
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting rule at line %d (\"%s\")\n",
			 yy_rule_linenum[yy_act], yy___text );
#else
			yy___stderr <<"--accepting rule at line "
                          <<(int)yy_rule_linenum[yy_act]
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER -1 )
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting default rule (\"%s\")\n",
			 yy___text );
#else
			yy___stderr <<"--accepting default rule"
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER )
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , "--(end of buffer or a NUL)\n" );
#else
			yy___stderr <<"--(end of buffer or a NUL)"<<endl;
#endif
		else
#ifndef YY_PDDL_Scanner_IOSTREAM
			fprintf( yy___stderr , "--EOF\n" );
#else
			yy___stderr <<"--EOF"<<endl;
#endif
		}
#endif
	switch ( yy_act )
	    {
/* % actions go here */ 
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
#line 42 "ppddl.lex"
;
	YY_BREAK
case 2:
#line 43 "ppddl.lex"
{ _line_no++;
                             if( _trace_line )
                                 cout << endl << "LINE: " << _line_no << endl;
                           }
	YY_BREAK
case 3:
#line 47 "ppddl.lex"
{ _line_no++;
                             if( _trace_line )
                                 cout << endl << "LINE: " << _line_no << endl;
                           }
	YY_BREAK
case 4:
#line 52 "ppddl.lex"
{ return PDDL_Parser::TK_OPEN; }
	YY_BREAK
case 5:
#line 53 "ppddl.lex"
{ return PDDL_Parser::TK_CLOSE; }
	YY_BREAK
case 6:
#line 54 "ppddl.lex"
{ return PDDL_Parser::TK_OPEN_SQ; }
	YY_BREAK
case 7:
#line 55 "ppddl.lex"
{ return PDDL_Parser::TK_CLOSE_SQ; }
	YY_BREAK
case 8:
#line 56 "ppddl.lex"
{ return PDDL_Parser::TK_HYPHEN; }
	YY_BREAK
case 9:
#line 57 "ppddl.lex"
{ return PDDL_Parser::TK_EQ; }
	YY_BREAK
case 10:
#line 59 "ppddl.lex"
{ return PDDL_Parser::KW_DEFINE; }
	YY_BREAK
case 11:
#line 60 "ppddl.lex"
{ return PDDL_Parser::KW_DOMAIN; }
	YY_BREAK
case 12:
#line 61 "ppddl.lex"
{ return PDDL_Parser::KW_REQS; }
	YY_BREAK
case 13:
#line 62 "ppddl.lex"
{ return PDDL_Parser::KW_TYPES; }
	YY_BREAK
case 14:
#line 63 "ppddl.lex"
{ return PDDL_Parser::KW_CONSTANTS; }
	YY_BREAK
case 15:
#line 64 "ppddl.lex"
{ return PDDL_Parser::KW_PREDS; }
	YY_BREAK
case 16:
#line 65 "ppddl.lex"
{ return PDDL_Parser::KW_OBSERVABLE; }
	YY_BREAK
case 17:
#line 66 "ppddl.lex"
{ return PDDL_Parser::KW_STICKY; }
	YY_BREAK
case 18:
#line 67 "ppddl.lex"
{ return PDDL_Parser::KW_FLUENTS; }
	YY_BREAK
case 19:
#line 68 "ppddl.lex"
{ return PDDL_Parser::KW_ACTION; }
	YY_BREAK
case 20:
#line 69 "ppddl.lex"
{ return PDDL_Parser::KW_AXIOM; }
	YY_BREAK
case 21:
#line 70 "ppddl.lex"
{ return PDDL_Parser::KW_SENSOR; }
	YY_BREAK
case 22:
#line 71 "ppddl.lex"
{ return PDDL_Parser::KW_ARGS; }
	YY_BREAK
case 23:
#line 72 "ppddl.lex"
{ return PDDL_Parser::KW_PRE; }
	YY_BREAK
case 24:
#line 73 "ppddl.lex"
{ return PDDL_Parser::KW_EFFECT; }
	YY_BREAK
case 25:
#line 74 "ppddl.lex"
{ return PDDL_Parser::KW_COND; }
	YY_BREAK
case 26:
#line 75 "ppddl.lex"
{ return PDDL_Parser::KW_SENSE; }
	YY_BREAK
case 27:
#line 76 "ppddl.lex"
{ return PDDL_Parser::KW_OBSERVE; }
	YY_BREAK
case 28:
#line 77 "ppddl.lex"
{ return PDDL_Parser::KW_BODY; }
	YY_BREAK
case 29:
#line 78 "ppddl.lex"
{ return PDDL_Parser::KW_HEAD; }
	YY_BREAK
case 30:
#line 79 "ppddl.lex"
{ return PDDL_Parser::KW_TRUE; }
	YY_BREAK
case 31:
#line 80 "ppddl.lex"
{ return PDDL_Parser::KW_FALSE; }
	YY_BREAK
case 32:
#line 81 "ppddl.lex"
{ return PDDL_Parser::KW_AND; }
	YY_BREAK
case 33:
#line 82 "ppddl.lex"
{ return PDDL_Parser::KW_EXISTS; }
	YY_BREAK
case 34:
#line 83 "ppddl.lex"
{ return PDDL_Parser::KW_FORALL; }
	YY_BREAK
case 35:
#line 84 "ppddl.lex"
{ return PDDL_Parser::KW_NOT; }
	YY_BREAK
case 36:
#line 85 "ppddl.lex"
{ return PDDL_Parser::KW_WHEN; }
	YY_BREAK
case 37:
#line 86 "ppddl.lex"
{ return PDDL_Parser::KW_INVARIANT; }
	YY_BREAK
case 38:
#line 87 "ppddl.lex"
{ return PDDL_Parser::KW_AT_LEAST_ONE; }
	YY_BREAK
case 39:
#line 88 "ppddl.lex"
{ return PDDL_Parser::KW_AT_MOST_ONE; }
	YY_BREAK
case 40:
#line 89 "ppddl.lex"
{ return PDDL_Parser::KW_EXACTLY_ONE; }
	YY_BREAK
case 41:
#line 90 "ppddl.lex"
{ return PDDL_Parser::KW_OR; }
	YY_BREAK
case 42:
#line 91 "ppddl.lex"
{ return PDDL_Parser::KW_ONEOF; }
	YY_BREAK
case 43:
#line 92 "ppddl.lex"
{ return PDDL_Parser::KW_UNKNOWN; }
	YY_BREAK
case 44:
#line 93 "ppddl.lex"
{ return PDDL_Parser::KW_PROBLEM; }
	YY_BREAK
case 45:
#line 94 "ppddl.lex"
{ return PDDL_Parser::KW_FORDOMAIN; }
	YY_BREAK
case 46:
#line 95 "ppddl.lex"
{ return PDDL_Parser::KW_OBJECTS; }
	YY_BREAK
case 47:
#line 96 "ppddl.lex"
{ return PDDL_Parser::KW_INIT; }
	YY_BREAK
case 48:
#line 97 "ppddl.lex"
{ return PDDL_Parser::KW_HIDDEN; }
	YY_BREAK
case 49:
#line 98 "ppddl.lex"
{ return PDDL_Parser::KW_GOAL; }
	YY_BREAK
case 50:
#line 100 "ppddl.lex"
{ return PDDL_Parser::KW_TRANSLATION; }
	YY_BREAK
case 51:
#line 101 "ppddl.lex"
{ return PDDL_Parser::KW_VARIABLE; }
	YY_BREAK
case 52:
#line 102 "ppddl.lex"
{ return PDDL_Parser::KW_OBS_VARIABLE; }
	YY_BREAK
case 53:
#line 103 "ppddl.lex"
{ return PDDL_Parser::KW_VGROUP; }
	YY_BREAK
case 54:
#line 104 "ppddl.lex"
{ return PDDL_Parser::KW_SENSING; }
	YY_BREAK
case 55:
#line 105 "ppddl.lex"
{ return PDDL_Parser::KW_DEFAULT_SENSING; }
	YY_BREAK
case 56:
#line 106 "ppddl.lex"
{ return PDDL_Parser::KW_MODEL_FOR; }
	YY_BREAK
case 57:
#line 107 "ppddl.lex"
{ return PDDL_Parser::KW_SUCH_THAT; }
	YY_BREAK
case 58:
#line 110 "ppddl.lex"
{ val.sym = _tab.inserta(yytext);
             if( val.sym->val == 0 )
                 return PDDL_Parser::TK_NEW_VAR_SYMBOL;
             if( ((PDDL_Base::Symbol*)val.sym->val)->sym_class_ == PDDL_Base::sym_variable )
                 return PDDL_Parser::TK_VAR_SYMBOL;
             return PDDL_Parser::TK_NEW_VAR_SYMBOL;
           }
	YY_BREAK
case 59:
#line 118 "ppddl.lex"
{ val.sym = _tab.inserta(yytext);
             return PDDL_Parser::TK_KEYWORD;
           }
	YY_BREAK
case 60:
#line 122 "ppddl.lex"
{ val.sym = _tab.inserta(yytext);
             if( val.sym->val == 0 ) {
                 return PDDL_Parser::TK_NEW_SYMBOL;
             } else {
                 switch (((PDDL_Base::Symbol*)val.sym->val)->sym_class_) {
                   case PDDL_Base::sym_object:
                     return PDDL_Parser::TK_OBJ_SYMBOL;
                   case PDDL_Base::sym_typename:
                     return PDDL_Parser::TK_TYPE_SYMBOL;
                   case PDDL_Base::sym_predicate:
                     return PDDL_Parser::TK_PRED_SYMBOL;
                   case PDDL_Base::sym_action:
                     return PDDL_Parser::TK_ACTION_SYMBOL;
                   case PDDL_Base::sym_sensor:
                     return PDDL_Parser::TK_SENSOR_SYMBOL;
                   case PDDL_Base::sym_axiom:
                     return PDDL_Parser::TK_AXIOM_SYMBOL;
                   case PDDL_Base::sym_varname:
                     return PDDL_Parser::TK_VARNAME_SYMBOL;
                   default:
                     return PDDL_Parser::TK_MISC_SYMBOL;
                 }
             }
           }
	YY_BREAK
case 61:
#line 147 "ppddl.lex"
{ val.ival = atoi(yytext); return PDDL_Parser::TK_INT; }
	YY_BREAK
case 62:
#line 149 "ppddl.lex"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();
#line 493 "/usr/local/lib/flexskel.cc"

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yy___text - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yy___text + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yy___text + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
/* % code to do backtracking for compressed tables and set up yy_cp goes here */ 
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
#line 541 "/usr/local/lib/flexskel.cc"
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yy___text,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yy___text + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yy___text + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#if YY_PDDL_Scanner_DEBUG != 0
#ifndef YY_PDDL_Scanner_IOSTREAM
		fprintf(yy___stderr , "action # %d\n", yy_act );
#else
		yy___stderr <<"action # "<<(int)yy_act<<endl;
#endif
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
	yyterminate();/* avoid the no return value error message on MS-C7/dos */
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
#ifndef YY_USE_CLASS
static int yy_get_next_buffer()
#else
int YY_PDDL_Scanner_CLASS::yy_get_next_buffer()
#endif
    {
    register YY_PDDL_Scanner_CHAR *dest = YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf;
    register YY_PDDL_Scanner_CHAR *source = yy___text - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yy___text;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( YY_PDDL_Scanner_CURRENT_BUFFER->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    YY_PDDL_Scanner_CURRENT_BUFFER->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    YY_PDDL_Scanner_CURRENT_BUFFER->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yy___text begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yy___text = &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state()
#else
long YY_PDDL_Scanner_CLASS::yy_get_previous_state_()
#endif
    {
    register yy_state_type yy_current_state;
    register YY_PDDL_Scanner_CHAR *yy_cp;

/* % code to get the start state into yy_current_state goes here */ 
    yy_current_state = yy_start;
#line 717 "/usr/local/lib/flexskel.cc"

    for ( yy_cp = yy___text + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
/* % code to find the next state goes here */ 
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 335 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
#line 721 "/usr/local/lib/flexskel.cc"
	}

#ifndef YY_USE_CLASS
    return ( yy_current_state );
#else
    return (long)( yy_current_state );
#endif
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif
#else
long YY_PDDL_Scanner_CLASS::yy_try_NUL_trans_(long yy_current_state_)
#endif

    {
#ifndef YY_USE_CLASS
#else
    yy_state_type yy_current_state=(yy_state_type)yy_current_state_;
#endif
    register int yy_is_jam;
/* % code to find the next state, and perhaps do backtracking, goes here */ 
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 335 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 334);
#line 755 "/usr/local/lib/flexskel.cc"

#ifndef YY_USE_CLASS
    return ( yy_is_jam ? 0 : yy_current_state );
#else
    return (long)( yy_is_jam ? 0 : yy_current_state );
#endif
    }

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static void yyunput( YY_PDDL_Scanner_CHAR c, register YY_PDDL_Scanner_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_PDDL_Scanner_CHAR c;
register YY_PDDL_Scanner_CHAR *yy_bp;
#endif
#else
void YY_PDDL_Scanner_CLASS::yyunput( YY_PDDL_Scanner_CHAR c, YY_PDDL_Scanner_CHAR *yy_bp )
#endif

    {
    register YY_PDDL_Scanner_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yy___text */
    *yy_cp = yy_hold_char;

    if ( yy_cp < YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_PDDL_Scanner_CHAR *dest =
	    &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_size + 2];
	register YY_PDDL_Scanner_CHAR *source =
	    &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[number_to_move];

	while ( source > YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_size;

	if ( yy_cp < YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yy___text again */
    }

#ifndef YY_USE_CLASS
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
#else
int YY_PDDL_Scanner_CLASS::input()
#endif
    {
    int c;
    YY_PDDL_Scanner_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &YY_PDDL_Scanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yy___text = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yy___text + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yy___text + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
#else
		    YY_FATAL_ERROR( "unexpected last match in YY_PDDL_Scanner_CLASS::input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_RESTART( YY_PDDL_Scanner_IFILE  *input_file )
#else
void YY_PDDL_Scanner_RESTART( input_file )
YY_PDDL_Scanner_IFILE  *input_file;
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_RESTART ( YY_PDDL_Scanner_IFILE  *input_file )
#endif

    {
    YY_PDDL_Scanner_INIT_BUFFER( YY_PDDL_Scanner_CURRENT_BUFFER, input_file );
    YY_PDDL_Scanner_LOAD_BUFFER_STATE();
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#else
void YY_PDDL_Scanner_SWITCH_TO_BUFFER( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#endif

    {
    if ( YY_PDDL_Scanner_CURRENT_BUFFER == new_buffer )
	return;

    if ( YY_PDDL_Scanner_CURRENT_BUFFER )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_pos = yy_c_buf_p;
	YY_PDDL_Scanner_CURRENT_BUFFER->yy_n_chars = yy_n_chars;
	}

    YY_PDDL_Scanner_CURRENT_BUFFER = new_buffer;
    YY_PDDL_Scanner_LOAD_BUFFER_STATE();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_LOAD_BUFFER_STATE( void )
#else
void YY_PDDL_Scanner_LOAD_BUFFER_STATE()
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_LOAD_BUFFER_STATE(  )
#endif

    {
    yy_n_chars = YY_PDDL_Scanner_CURRENT_BUFFER->yy_n_chars;
    yy___text = yy_c_buf_p = YY_PDDL_Scanner_CURRENT_BUFFER->yy_buf_pos;
    yy___in = YY_PDDL_Scanner_CURRENT_BUFFER->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE YY_PDDL_Scanner_CREATE_BUFFER( YY_PDDL_Scanner_IFILE  *file, int size )
#else
YY_BUFFER_STATE YY_PDDL_Scanner_CREATE_BUFFER( file, size )
YY_PDDL_Scanner_IFILE  *file;
int size;
#endif
#else
YY_BUFFER_STATE YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_CREATE_BUFFER( YY_PDDL_Scanner_IFILE  *file, int size )
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in YY_PDDL_Scanner_CREATE_BUFFER()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_PDDL_Scanner_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in YY_PDDL_Scanner_CREATE_BUFFER()" );

    YY_PDDL_Scanner_INIT_BUFFER( b, file );

    return ( b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_DELETE_BUFFER( YY_BUFFER_STATE b )
#else
void YY_PDDL_Scanner_DELETE_BUFFER( b )
YY_BUFFER_STATE b;
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_DELETE_BUFFER( YY_BUFFER_STATE b )
#endif

    {
    if ( b == YY_PDDL_Scanner_CURRENT_BUFFER )
	YY_PDDL_Scanner_CURRENT_BUFFER = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_PDDL_Scanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_PDDL_Scanner_IFILE  *file )
#else
void YY_PDDL_Scanner_INIT_BUFFER( b, file )
YY_BUFFER_STATE b;
YY_PDDL_Scanner_IFILE  *file;
#endif
#else
void YY_PDDL_Scanner_CLASS::YY_PDDL_Scanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_PDDL_Scanner_IFILE  *file)
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
#line 149 "ppddl.lex"


/*{FLOAT}    { val.rval = A_TO_NN(yytext); return PDDL_Parser::TK_FLOAT; }*/

int yywrap() {
    return 1;
}

void PDDL_Scanner::open_file(char* name, bool trace) {
    yyin = fopen(name, "r");
    if( !yyin ) {
        cout << Utils::error() << "can't open " << name << endl;
        exit(255);
    }
    _filename = name;
    if( _reset ) yy_init_buffer(YY_PDDL_Scanner_CURRENT_BUFFER, yyin);
    _reset = true;
    _line_no = 1;
    _trace_line = trace;
    yy_flex_debug = trace;
}

void PDDL_Scanner::close_file() {
    if( _filename != 0 ) {
        fclose(yyin);
        _filename = 0;
    }
}

